name: Deploy pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -

    - name: Install mariadb dependencies needed for connector
      run: sudo apt-get install -y libmariadb3 libmariadb-dev

    - name: Install dependencies
      run: poetry install --only main

    - name: create pages
      run: poetry run ./make_pages.sh

    - name: Commit result
      run: |
        git config --global user.name 'Github Action'
        git config --global user.email 'github-action@users.noreply.github.com'
        git commit -am "Generated new site release"
        git push
